- name: "type: mod request"
  description: "Request for a mod to be added"
  color: "2c4175"
- name: "type: bug report"
  description: "Report a bug"
  color: "ae120d"
- name: "type: feature request"
  description: "Request a feature to be added"
  color: "20dca9"
- name: "status: in progress"
  description: "This issue or PR is in progress"
  color: "2020dc"
- name: "status: needs testing"
  description: "This bugfix needs to be tested"
  color: "900C3F"
- name: "bug: unverified"
  description: "This bug report still needs to be verified"
  color: "750606"
- name: "bug: confirmed"
  description: "This bug report has been verified"
  color: "670a0a"
