name = "FullMash"
author = "Jaron Zijlstra"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d056a68c28e164395699b97d2069369d5647a4b29749ede8295748ede08a7f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.119"

[options]
acceptable-game-versions = ["1.21.1"]
