name = "FullMash"
author = "Jaron Zijlstra"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93af1a4ba03c9964b6ad45ad5cefd412f77c3373dbdf1d06a1e8b5dcf8877039"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"

[options]
acceptable-game-versions = ["1.21.1"]
