name = "FullMash"
author = "Jaron Zijlstra"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1ab2f8694c05e8c83583da6cc1acd3600cb3a15504e605221e69676df51e7b0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.97"

[options]
acceptable-game-versions = ["1.21.1"]
