name = "FullMash"
author = "Jaron Zijlstra"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55681a7a3e98ce91eccebf4df1d271cd8900f2113f40047dbfccb4e89db70ef0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.119"

[options]
acceptable-game-versions = ["1.21.1"]
