name = "asdhell"
author = "Jaron Zijlstra"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b35793ca80c5854db540e4ae61e409490303cbe6f12e269e46a447ab6c1a69c4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.94"

[options]
acceptable-game-versions = ["1.21.1"]
