name = "asdhell"
author = "Jaron Zijlstra"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f339a46de08f4a70720131f4aacd718c430522354a7748cfa7517b050021fc80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.94"

[options]
acceptable-game-versions = ["1.21.1"]
