name = "fullmash"
author = "Jaron Zijlstra"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51775ed114d5eb031e7b0ad145500869fffc042582cb08409b30bc35de4e020d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.94"

[options]
acceptable-game-versions = ["1.21.1"]
