name = "asdhell"
author = "Jaron Zijlstra"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bba01f46a5c56005505c7d6d463f23aa9de2ab2eca534cf925195df6ca7d1c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.94"

[options]
acceptable-game-versions = ["1.21.1"]
