name = "FullMash"
author = "Jaron Zijlstra"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a391efdac96613a33e0754cb1d60a354dbd80048f3d6e80c5e8b9e60172a4fc7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.97"

[options]
acceptable-game-versions = ["1.21.1"]
