name = "FullMash"
author = "Jaron Zijlstra"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95c5c1f01a71cd9d4cb372a27462cb0f8fc1ce830dec6adb87bdc06d11019950"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.124"

[options]
acceptable-game-versions = ["1.21.1"]
